CREATE TABLE leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_name text not null, -- Which of your clients gets this lead?
  customer_name text not null,
  customer_email text not null,
  message text,
  status text default 'new' -- new, contacted, closed
);
